name: example
description: nonogram_dart example
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

# Add regular dependencies here.
dependencies:
  nonogram_dart: 
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
